const myAge =26;
const earlyYears = 2;
earlyYear = earlyYears*10.5;
laterYears = myAge/2;
laterYears *=4;
console.log(earlyYear);
console.log(laterYears);
myAgeInDogYears = earlyYear + laterYears;
const myName = 'Qudsy';
myname = myName.toLowerCase();
console.log(myname);
console.log(`My Name is  ${myname}. I am ${myAge} years old in human years wich is ${myAgeInDogYears} years old in dog years.`);